services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - db
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
    ports:
      - "8080:8080"

  db:
    image: postgres:latest
    container_name: database
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
